[project]
name = "demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "vpype>=1.13",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
